name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # Run every 5 hours
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          token: ${{ secrets.FINE_GRAINED_PAT }} # Use fine-grained PAT for checkout
      - name: Set up OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Debug - List directory contents
        run: ls -la
      - name: Run Spigot with 30-second commits and workflow deletion
        # This condition ensures the step doesn't run if the commit message already contains "Auto commit every 30 seconds"
        # to prevent an infinite loop of workflow triggers from self-commits.
        if: "!contains(github.event.head_commit.message, 'Auto commit every 30 seconds')"
        env:
          FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
          REPO: ${{ github.repository }} # GITHUB_REPOSITORY is also available automatically
        run: |
          # Start playit agent in background
          # The user provided a hardcoded secret in the command, so we'll use that.
          # If playit.toml is truly needed, the secret should be written there.
          chmod +x playit-linux-amd64
          echo "Starting playit agent..."
          ./playit-linux-amd64 --secret dba8668ae0b663e88ff9da28add6b73bee79dc86697bc897614a4906e4fd21d2 &
          PLAYIT_PID=$!
          echo "Playit agent started with PID $PLAYIT_PID"

          # Download Minecraft server JAR
          LINK="https://github.com/IzzelAliz/Arclight/releases/download/FeudalKings%2F1.0.0/arclight-fabric-1.21.1-1.0.0-3457560.jar"
          JAR="${LINK##*/}"
          echo "Downloading $JAR from $LINK..."
          wget "$LINK" -O "$JAR"

          # Accept EULA (End User License Agreement) for Minecraft server
          echo "eula=true" > eula.txt

          # Start Minecraft server in background
          echo "Starting Minecraft server ($JAR)..."
          java -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Xms16G -Xmx16G -jar "$JAR" nogui 2>&1 | sed '/login:/s/.*/<REDACTED>/' &
          SPIGOT_PID=$!
          echo "Minecraft server started with PID $SPIGOT_PID"

          # Give the server some time to start and generate initial files
          echo "Waiting 60 seconds for server to initialize and generate files..."
          sleep 60

          # Function to commit and push changes
          commit_and_push() {
            echo "Checking for changes to commit..."
            # Use --porcelain to get machine-readable output; -n checks if string is non-empty
            if [[ -n $(git status --porcelain) ]]; then
              echo "Changes detected. Committing and pushing..."
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              git add -A # Stage all changes
              
              # Attempt to commit; check exit code
              git commit -m "Auto commit every 30 seconds"
              if [ $? -eq 0 ]; then
                echo "Changes committed successfully."
                # Attempt to push; check exit code
                git push https://x-access-token:${FINE_GRAINED_PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:main
                if [ $? -eq 0 ]; then
                  echo "Changes pushed successfully."
                else
                  echo "Error: Failed to push changes."
                  exit 1 # Exit with error if push fails
                fi
              else
                echo "Error: Failed to create commit. This might happen if there are no changes after all."
              fi
            else
              echo "No changes detected to commit."
            fi
          }

          # Function to delete auto-commit workflow runs
          delete_auto_commit_workflows() {
            echo "Attempting to delete old auto-commit workflow runs..."
            # Ensure `jq` is installed for JSON parsing. GitHub Actions runners usually have it.
            workflow_ids=$(curl -s -H "Authorization: token $FINE_GRAINED_PAT" \
              "https://api.github.com/repos/${REPO}/actions/runs" | \
              jq '.workflow_runs[] | select(.head_commit.message | contains("Auto commit every 30 seconds")) | .id')

            if [ -z "$workflow_ids" ]; then
              echo "No auto-commit workflow runs found to delete."
              return # Exit function if no IDs found
            fi

            for id in $workflow_ids; do
              echo "Deleting workflow run $id"
              curl -s -X DELETE -H "Authorization: token $FINE_GRAINED_PAT" \
                "https://api.github.com/repos/${REPO}/actions/runs/$id"
              if [ $? -ne 0 ]; then
                echo "Error deleting workflow run $id"
              fi
            done
          }

          # Loop to commit and delete workflows every 30 seconds
          while true; do
            sleep 30
            commit_and_push
            delete_auto_commit_workflows
            
            # Check if processes are still running
            # `kill -0 $SPIGOT_PID` sends signal 0, which checks if the process exists without killing it.
            if ! kill -0 $SPIGOT_PID 2>/dev/null; then
              echo "Spigot process has finished. Terminating the workflow."
              break
            fi
            if ! kill -0 $PLAYIT_PID 2>/dev/null; then
              echo "Playit process has finished. Terminating the workflow."
              break
            fi
          done
